development:
  adapter: mysql2
  database: cookbook_dev
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: cookbook_Test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: cookbook_Prod
  username: root
  password: root
  host: localhost
